//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attractions.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttractionsListing
    {
        public AttractionsListing()
        {
            this.AttractionsUsageTypes = new HashSet<AttractionsUsageType>();
        }
    
        public long ListingId { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public Nullable<int> UserRating { get; set; }
        public Nullable<int> Ranking { get; set; }
        public Nullable<int> PromoRanking { get; set; }
        public int LocationId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual AttractionsCategory AttractionsCategory { get; set; }
        public virtual AttractionsStatu AttractionsStatu { get; set; }
        public virtual ICollection<AttractionsUsageType> AttractionsUsageTypes { get; set; }
        public virtual AttractionsLocation AttractionsLocation { get; set; }
    }
}
