//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attractions.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttractionsUsageType
    {
        public AttractionsUsageType()
        {
            this.AttractionsListings = new HashSet<AttractionsListing>();
        }
    
        public int UsageTypeId { get; set; }
        public string UsageTypeName { get; set; }
        public string FromAge { get; set; }
        public string ToAge { get; set; }
        public Nullable<int> MenWomenAllowed { get; set; }
    
        public virtual ICollection<AttractionsListing> AttractionsListings { get; set; }
    }
}
