//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attractions.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttractionsLocation
    {
        public AttractionsLocation()
        {
            this.AttractionsListings = new HashSet<AttractionsListing>();
        }
    
        public int LocationId { get; set; }
        public string place_id { get; set; }
        public string short_name { get; set; }
        public string long_name { get; set; }
        public string alt { get; set; }
        public string types { get; set; }
    
        public virtual ICollection<AttractionsListing> AttractionsListings { get; set; }
    }
}
