//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attractions.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttractionsCategory
    {
        public AttractionsCategory()
        {
            this.AttractionsListings = new HashSet<AttractionsListing>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<AttractionsListing> AttractionsListings { get; set; }
    }
}
