//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attractions.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AttractionsEntities : DbContext
    {
        public AttractionsEntities()
            : base("name=AttractionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AttractionsCategory> AttractionsCategories { get; set; }
        public DbSet<AttractionsListing> AttractionsListings { get; set; }
        public DbSet<AttractionsLocation> AttractionsLocations { get; set; }
        public DbSet<AttractionsStatu> AttractionsStatus { get; set; }
        public DbSet<AttractionsUsageType> AttractionsUsageTypes { get; set; }
    }
}
